@startuml

abstract class Command{
  + apply(robot:Robot) : void
}

class GoForward
class TurnLeft

Command <|-- GoForward
Command <|-- TurnLeft

Robot -> Command




class Robot{
  sendCommand(cmd : Command) : void
}



@enduml
